/* CRIA ESQUEMA */
DROP DATABASE IF EXISTS INFO_CRIMINAIS_SP;

CREATE DATABASE INFO_CRIMINAIS_SP;

USE INFO_CRIMINAIS_SP;

DROP TABLE IF EXISTS DELEGACIA;

CREATE TABLE DELEGACIA (
        ID_DELEGACIA        INT NOT NULL,
        NOME                VARCHAR(100) NOT NULL,
        CIRCUNSCRICAO       VARCHAR(100) NULL,
        CONSTRAINT PK_DELEGACIA
                PRIMARY KEY (ID_DELEGACIA)
);

DROP TABLE IF EXISTS BO;

CREATE TABLE BO (
		ID_BO					INT NOT NULL,
		NUM_BO					INT,
        ANO_BO					INT,
        NUM_BOLETIM				VARCHAR(25),
        NUM_BOLETIM_PRINCIPAL	VARCHAR(45),
        DATA_EMITIDO			DATETIME,
        DATA_INICIADO			DATETIME,
        DATA_ELABORACAO			DATETIME,
        AUTORIA					VARCHAR(45),
        SOLUCAO					VARCHAR(200),
        DELEGACIA 				INT,
        CONSTRAINT PK_BO
				PRIMARY KEY (ID_BO)
);

ALTER TABLE BO
        ADD CONSTRAINT FK01_DELEGACIA_BO
                FOREIGN KEY (DELEGACIA)
                        REFERENCES DELEGACIA (ID_DELEGACIA)
                        ON DELETE SET NULL;

DROP TABLE IF EXISTS ENDERECO;

CREATE TABLE ENDERECO (
		ID_ENDERECO 			INT NOT NULL,
        LOGRADOURO				VARCHAR(100),
        NUMERO 					INT,
        BAIRRO					VARCHAR(100),
        CIDADE					VARCHAR(100),
        UF						VARCHAR(3),
        LATITUDE				DOUBLE,
        LONGITUDE				DOUBLE,
        DESCRICAO_LOCAL			VARCHAR(100),
        CONSTRAINT PK_ENDERECO
				PRIMARY KEY (ID_ENDERECO)
);

DROP TABLE IF EXISTS OCORRENCIA;

CREATE TABLE OCORRENCIA (
		ID_OCORRENCIA			INT NOT NULL,
        DATA_OCORRENCIA 		DATE,
        PERIODO_OCORRENCIA		VARCHAR(45),
        DATA_COMUNICACAO		DATE,
		ESPECIE					VARCHAR(100),
        RUBRICA					VARCHAR(200),
        DESDOBRAMENTO			VARCHAR(200),
        STATUS_OCORR			VARCHAR(25),
        FLAGRANTE				VARCHAR(4),
        EXAME 					VARCHAR(10),
        ENDERECO_OCORRENCIA		INT,
        BOLETIM_OCORRENCIA		INT,
        CONSTRAINT PK_OCORRENCIA
				PRIMARY KEY (ID_OCORRENCIA),
		CONSTRAINT FK02_BO_OCORR
				FOREIGN KEY (BOLETIM_OCORRENCIA)
						REFERENCES BO (ID_BO)
                        ON DELETE CASCADE,
		CONSTRAINT FK01_ENDERECO_OCORR
				FOREIGN KEY (ENDERECO_OCORRENCIA)
						REFERENCES ENDERECO (ID_ENDERECO)
                        ON DELETE CASCADE
);

DROP TABLE IF EXISTS PESSOA;

CREATE TABLE PESSOA (
		ID_PESSOA				INT NOT NULL,
        NOME					VARCHAR(100),
        RG_NUM					INT,
        RG_UF					VARCHAR(2),
        TIPO_PESSOA				VARCHAR(25),
        VITIMA_FATAL			VARCHAR(4),
        NACIONALIDADE			VARCHAR(20),
        NATURALIDADE			VARCHAR(30),
        DATA_NASCIMENTO			VARCHAR(10),
        IDADE					INT,
        TIPO_IDADE				VARCHAR(5),
        SEXO					VARCHAR(45),
        ESTADO_CIVIL			VARCHAR(15),
        PROFISSAO				VARCHAR(30),
        GRAU_INSTRUCAO			VARCHAR(30),
        COR_DE_PELE				VARCHAR(30),
        NATUREZA_VINCULADA		VARCHAR(100),
        TIPO_VINCULO			VARCHAR(15),
        CONSTRAINT PK_PESSOA
				PRIMARY KEY (ID_PESSOA)
);

DROP TABLE IF EXISTS VEICULO;

CREATE TABLE VEICULO (
		PLACA_VEICULO		VARCHAR(50) NOT NULL,
        UF					VARCHAR(3),
        CIDADE				VARCHAR(45),
        COR					VARCHAR(20),
        MARCA				VARCHAR(100),
        ANO_FABRICACAO		INT,
        ANO_MODELO			INT,
        TIPO_VEICULO		VARCHAR(100),
        CONSTRAINT PK_VEICULO
				PRIMARY KEY (PLACA_VEICULO)
);

DROP TABLE IF EXISTS OBJETO;

CREATE TABLE OBJETO (
		ID_OBJETO		INT NOT NULL,
        TIPO_OBJETO		VARCHAR(45),
        VEICULO_PLACA	VARCHAR(50),
        CONSTRAINT PK_OBJETO
				PRIMARY KEY (ID_OBJETO),
		CONSTRAINT FK01_VPLACA_OBJETO
				FOREIGN KEY (VEICULO_PLACA)
						REFERENCES VEICULO (PLACA_VEICULO)
                        ON DELETE SET NULL
);

DROP TABLE IF EXISTS LESAO_CORPORAL;

CREATE TABLE LESAO_CORPORAL (
		ID_OCORRENCIA 		INT NOT NULL,
        SEGUIDA_MORTE		VARCHAR(40),
        PESSOA_ID			INT,
        CONSTRAINT PK_LESAO
				PRIMARY KEY (ID_OCORRENCIA),
		CONSTRAINT FK01_OCORRENCIA_LESAO
				FOREIGN KEY (ID_OCORRENCIA)
						REFERENCES OCORRENCIA (ID_OCORRENCIA)
                        ON DELETE CASCADE,
		CONSTRAINT FK02_PESSOA_LESAO
				FOREIGN KEY (PESSOA_ID)
						REFERENCES PESSOA (ID_PESSOA)
                        ON DELETE SET NULL
);

DROP TABLE IF EXISTS MORTE_SUSPEITA;

CREATE TABLE MORTE_SUSPEITA (
		ID_OCORRENCIA 		INT NOT NULL,
        PESSOA_ID			INT,
        TIPO_MORTE_SUSPEITA	VARCHAR(200),
        CONSTRAINT PK_MORTE_SUSPEITA
				PRIMARY KEY (ID_OCORRENCIA),
		CONSTRAINT FK01_OCORRENCIA_MORTESUS
				FOREIGN KEY (ID_OCORRENCIA)
						REFERENCES OCORRENCIA (ID_OCORRENCIA)
                        ON DELETE CASCADE,
		CONSTRAINT FK02_PESSOA_MORTESUS
				FOREIGN KEY (PESSOA_ID)
						REFERENCES PESSOA (ID_PESSOA)
                        ON DELETE SET NULL
);

DROP TABLE IF EXISTS HOMICIDIO;

CREATE TABLE HOMICIDIO (
		ID_OCORRENCIA 		INT NOT NULL,
        PESSOA_ID			INT,
        TIPO_HOMICIDIO		VARCHAR(45),
        CONSTRAINT PK_HOMICIDIO
				PRIMARY KEY (ID_OCORRENCIA),
		CONSTRAINT FK01_OCORRENCIA_HOMICIDIO
				FOREIGN KEY (ID_OCORRENCIA)
						REFERENCES OCORRENCIA (ID_OCORRENCIA)
                        ON DELETE CASCADE,
		CONSTRAINT FK02_PESSOA_HOMICIDIO
				FOREIGN KEY (PESSOA_ID)
						REFERENCES PESSOA (ID_PESSOA)
                        ON DELETE SET NULL
);
DROP TABLE IF EXISTS ROUBO;

CREATE TABLE ROUBO (
		ID_OCORRENCIA 		INT NOT NULL,
        PESSOA_ID			INT,
        OBJETO_ID			INT,
        CONSTRAINT PK_ROUBO
				PRIMARY KEY (ID_OCORRENCIA),
		CONSTRAINT FK01_OCORRENCIA_ROUBO
				FOREIGN KEY (ID_OCORRENCIA)
						REFERENCES OCORRENCIA (ID_OCORRENCIA)
                        ON DELETE CASCADE,
		CONSTRAINT FK02_PESSOA_ROUBO
				FOREIGN KEY (PESSOA_ID)
						REFERENCES PESSOA (ID_PESSOA)
                        ON DELETE SET NULL,
		CONSTRAINT FK03_OBJETO_ROUBO
				FOREIGN KEY (OBJETO_ID)
						REFERENCES OBJETO (ID_OBJETO)
                        ON DELETE CASCADE
);

DROP TABLE IF EXISTS FURTO;

CREATE TABLE FURTO (
		ID_OCORRENCIA 		INT NOT NULL,
        PESSOA_ID			INT,
        OBJETO_ID			INT,
        CONSTRAINT PK_ROUBO
				PRIMARY KEY (ID_OCORRENCIA),
		CONSTRAINT FK01_OCORRENCIA_FURTO
				FOREIGN KEY (ID_OCORRENCIA)
						REFERENCES OCORRENCIA (ID_OCORRENCIA)
                        ON DELETE CASCADE,
		CONSTRAINT FK02_PESSOA_FURTO
				FOREIGN KEY (PESSOA_ID)
						REFERENCES PESSOA (ID_PESSOA)
                        ON DELETE SET NULL,
		CONSTRAINT FK03_OBJETO_FURTO
				FOREIGN KEY (OBJETO_ID)
						REFERENCES OBJETO (ID_OBJETO)
                        ON DELETE CASCADE
);


DROP TABLE IF EXISTS OUTRAS_OCORRENCIAS;

CREATE TABLE OUTRAS_OCORRENCIAS (
		ID_OCORRENCIA 		INT NOT NULL,
        PESSOA_ID			INT,
        CONSTRAINT PK_OUTRAS_O
				PRIMARY KEY (ID_OCORRENCIA),
		CONSTRAINT FK01_OCORRENCIA_OUTRAS_O
				FOREIGN KEY (ID_OCORRENCIA)
						REFERENCES OCORRENCIA (ID_OCORRENCIA)
                        ON DELETE CASCADE,
		CONSTRAINT FK02_PESSOA_OUTRAS_O
				FOREIGN KEY (PESSOA_ID)
						REFERENCES PESSOA (ID_PESSOA)
                        ON DELETE SET NULL
);

DROP TABLE IF EXISTS DECLARACAO_OBITO;

CREATE TABLE DECLARACAO_OBITO (
		ID_DECLARACAO_OBITO		INT,
        NUM_DECL_OBITO			INT,
        CONCLUSAO				VARCHAR(250),
        CONSTRAINT PK_DECLARACAO_OBITO
				PRIMARY KEY (ID_DECLARACAO_OBITO)
);

DROP TABLE IF EXISTS REGISTRO_OBITO_IML;

CREATE TABLE REGISTRO_OBITO_IML (
		ID_REGISTRO_OBITO		INT NOT NULL,
        DATA_ENTRADA_IML		DATETIME NOT NULL,
        NUM_LAUDO				INT NOT NULL,
        ANO_LAUDO				INT NOT NULL,
        DECLARACAO_OBITO_ID		INT NOT NULL,
        OCORRENCIA_ID			INT NOT NULL,
        CONSTRAINT PK_REGISTRO_OBITO_IML
				PRIMARY KEY (ID_REGISTRO_OBITO),
        CONSTRAINT FK01_DECLARACAO_REGISTRO
				FOREIGN KEY (DECLARACAO_OBITO_ID)
						REFERENCES DECLARACAO_OBITO (ID_DECLARACAO_OBITO)
                        ON DELETE CASCADE,
		CONSTRAINT FK02_OCORRENCIA_REGISTRO
				FOREIGN KEY (OCORRENCIA_ID)
						REFERENCES OCORRENCIA (ID_OCORRENCIA)
                        ON DELETE CASCADE
);



/* INSERIR DADOS */

-- DELEGACIA
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/delegacias.csv'
	INTO TABLE DELEGACIA
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (NOME, CIRCUNSCRICAO, ID_DELEGACIA);
    
SELECT * FROM DELEGACIA;


-- PESSOAS
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/pessoas.csv'
	INTO TABLE PESSOA
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (NOME, TIPO_PESSOA, VITIMA_FATAL, RG_NUM, RG_UF, NATURALIDADE, NACIONALIDADE, SEXO, @D_NASC, IDADE,
    ESTADO_CIVIL, PROFISSAO, GRAU_INSTRUCAO, COR_DE_PELE, NATUREZA_VINCULADA, TIPO_VINCULO, ID_PESSOA)
    SET DATA_NASCIMENTO = STR_TO_DATE(@D_NASC, '%Y-%m-%d');

-- SELECT * FROM PESSOA;

-- VEICULO
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/veiculo.csv'
	INTO TABLE VEICULO
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (PLACA_VEICULO, UF, CIDADE, COR, MARCA, ANO_FABRICACAO, ANO_MODELO, TIPO_VEICULO);

-- SELECT * FROM VEICULO;

-- OBJETO
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/objeto.csv'
	INTO TABLE OBJETO
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (TIPO_OBJETO, VEICULO_PLACA, ID_OBJETO);

-- SELECT * FROM OBJETO;

-- ENDERECO
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/endereco.csv'
	INTO TABLE ENDERECO
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (LOGRADOURO, NUMERO, BAIRRO, CIDADE, UF, LATITUDE, LONGITUDE, DESCRICAO_LOCAL, ID_ENDERECO);

-- SELECT * FROM ENDERECO;



-- BO
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/bo.csv'
	INTO TABLE BO
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (ANO_BO, NUM_BO, NUM_BOLETIM, @DATA_INI, @DATA_EMI, @DATA_ELAB, AUTORIA, NUM_BOLETIM_PRINCIPAL,
		SOLUCAO, DELEGACIA, ID_BO)
    SET DATA_INICIADO = STR_TO_DATE(@DATA_INI, '%d/%m/%Y %H:%i:%s'),
		DATA_EMITIDO = STR_TO_DATE(@DATA_EMI, '%d/%m/%Y %H:%i:%s'),
        DATA_ELABORACAO = STR_TO_DATE(@DATA_ELAB, '%d/%m/%Y %H:%i:%s');

-- SELECT * FROM BO;-- 

-- OCORRENCIA
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/ocorrencias.csv'
	INTO TABLE OCORRENCIA
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (BOLETIM_OCORRENCIA, @D_OCO, PERIODO_OCORRENCIA, @D_COM, FLAGRANTE, ENDERECO_OCORRENCIA, EXAME, ESPECIE, RUBRICA,
    DESDOBRAMENTO, STATUS_OCORR, ID_OCORRENCIA)
    SET DATA_OCORRENCIA = STR_TO_DATE(@D_OCO, '%d/%m/%Y'),
			DATA_COMUNICACAO = STR_TO_DATE(@D_COM, '%d/%m/%Y');
            
-- SELECT * FROM OCORRENCIA;

-- LESAO CORPORAL
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/les_corporal.csv'
	INTO TABLE LESAO_CORPORAL
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (ID_OCORRENCIA, SEGUIDA_MORTE, PESSOA_ID);
    
-- SELECT * FROM LESAO_CORPORAL;

-- MORTE SUSPEITA
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/morte_susp.csv'
	INTO TABLE MORTE_SUSPEITA
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (ID_OCORRENCIA, TIPO_MORTE_SUSPEITA, PESSOA_ID);
    
-- SELECT * FROM MORTE_SUSPEITA;

-- HOMICIDIO
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/homicidio.csv'
	INTO TABLE HOMICIDIO
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (ID_OCORRENCIA, TIPO_HOMICIDIO, PESSOA_ID);
    
-- SELECT * FROM HOMICIDIO;

-- ROUBO
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/roubo.csv'
	INTO TABLE ROUBO
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (ID_OCORRENCIA, PESSOA_ID, OBJETO_ID);
    
-- SELECT * FROM ROUBO;


-- FURTO
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/roubo.csv'
	INTO TABLE FURTO
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (ID_OCORRENCIA, PESSOA_ID, OBJETO_ID);

-- SELECT * FROM FURTO;

-- OUTRAS_OCORRENCIAS
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/outras_oco.csv'
	INTO TABLE OUTRAS_OCORRENCIAS
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (ID_OCORRENCIA, PESSOA_ID);

SELECT * FROM OUTRAS_OCORRENCIAS;


-- REGISTRO OBITO IML
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/declaracao_obito.csv'
	INTO TABLE DECLARACAO_OBITO
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (NUM_DECL_OBITO, CONCLUSAO, ID_DECLARACAO_OBITO);
    
-- SELECT * FROM DECLARACAO_OBITO;

-- REGISTRO OBITO IML
LOAD DATA LOCAL INFILE '/home/arabella/projetos/mc536/projeto 1/registro_obito_iml.csv'
	INTO TABLE REGISTRO_OBITO_IML
    CHARACTER SET 'UTF8'
    FIELDS TERMINATED BY '\t'
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (@D_ENTRADA, NUM_LAUDO, ANO_LAUDO, DECLARACAO_OBITO_ID, OCORRENCIA_ID, ID_REGISTRO_OBITO)
    SET DATA_ENTRADA_IML = STR_TO_DATE(@D_ENTRADA, '%d/%m/%Y %H:%i:%s');

-- SELECT * FROM REGISTRO_OBITO_IML;